FROM rembg-app:latest

WORKDIR /rembg

COPY . .

# RUN python -m pip install ".[gpu,cli]" --break-system-packages
RUN python3 -m pip install -e ".[gpu,cli]" -i https://pypi.tuna.tsinghua.edu.cn/simple

EXPOSE 7000
ENTRYPOINT ["rembg"]
CMD ["--help"]
